apiVersion:  v1 
kind:  ReplicationController 
metadata:
   name: nginzapp
   labels:
     app: nginxapp 
spec:
  replicas: 3
  selector:
    #matchlabels:
    app: nginx
  template:
    metadata: 
      name: nginxapp
      labels:
        app: nginxapp 
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
    