apiVersion: v1
kind: Pod
metadata:
  name: nginxnp
  namespace: amazons
  labels:
   app: nginxnp
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
   name: nodeport
   namespace: amazons
   labels:
     app: nodeport
spec:
    selector:
        app: nginxnp
    ports:
       - protocol: TCP
         port: 80
         targetPort: 80
    type: NodePort
---
apiVersion: v1
kind: namespace
metadata:
  name: amazons
  labels:
    app:amazons