apiVersion: v1
kind: Pod
metadata:
  name: git-pod
spec:
  volumes:
  - name: app-volume
    emptyDir: {}

  initContainers:
  - name: git-clone
    image: alpine/git
    args:
      - clone
      - https://github.com/gvarad/Kubernetes.git
      - /app
    volumeMounts:
    - name: app-volume
      mountPath: /app

  containers:
  - name: app
    image: node:18
    command: ["npm", "start"]
    workingDir: /app
    volumeMounts:
    - name: app-volume
      mountPath: /app
