apiVersion: v1
kind: ReplicationController
metadata:
   name: rc-flipkartapp
   labels:
     app: rc-flipkartapp
spec:
  replica: 3
  selector:
    app: flipkart
  template:
    metadata:
      name: flipkart
      labels:
        app: flipkart
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80