apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv 
  labels:
    app: pv 
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessMode:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostpath:
    path: "/mnt/data"
  ppersistentVolumeReclaimPolicy: Retain